### PR TITLE
send links to Jaeger reporter, if set

### PR DESCRIPTION
**Pull request by hughsimpson**
Also:
- ~Add a 'ChildOf' link type~ Removed for now
- Bump com.dimafeng libs in elasticsearch module to help the failing test
- Made the datadog test a little more forgiving (it appears that the type of exception thrown depends on the architecture or something)

Enables the following view in recent versions of Jaeger UI
Screenshot 2021-03-06 at 13 36 28

### CODE REVIEW

**Comment by SimunKaracic** [comment]
Nice PR, and thanks for the driveby fixes!
But this PR touches kamon-core, so we'll need to take a closer look at it!

Thanks for the patience :D

**Comment by hughsimpson** [comment]
If it speeds up the process of review I can just remove the `ChildOf` case object, since it's the only thing being touched in core, and FollowsFrom is almost as good for my purposes

**Comment by SimunKaracic** [comment]
Yes please remove ChildOf, without that this should be a no brainer to merge :)

**Comment by hughsimpson** [comment]
K reverted that. Will make a separate commit though

**Comment by SimunKaracic** [comment]
> K reverted that. May make a separate pr though - I'd still like ChildOf

Please do, and feel free to write the motivation for it, so we know what ChildOf brings to the table that can't be modelled with  FollowsFrom. 

Thanks for the contribution :)

**Comment by SimunKaracic** [comment]
Sorry for the conflicts! :D
If you have the time, fix them, if not, I'll deal with it tomorrow and merge :)

**Comment by hughsimpson** [comment]
No problem, will do now

**Comment by hughsimpson** [comment]
All done 👍

**Comment by SimunKaracic** [comment]
Great job on the whole PR, thanks for the contribution! :tada:

**Pull request merged**
