### PR TITLE
= core: don't throw MathError when auto-start is disabled for a module #300

### PR DESCRIPTION
**Pull request by trobert**

### CODE REVIEW

**Comment by dpsoft** [comment]
@trobert Thanks for this PR!!! Merged.

**Comment by trobert** [comment]
Super, thx !

**Comment by trobert** [comment]
@dpsoft Is it possible to merge it in java8 branch too ?
Should I re-open a PR in java8 ?

**Comment by dpsoft** [comment]
@trobert done!!

**Comment by trobert** [comment]
Thank you!

**Pull request merged**
