### PR TITLE
! core: cleanup entity on removal

### PR DESCRIPTION
**Pull request by nilsga**
Fixes https://github.com/kamon-io/Kamon/issues/227

### CODE REVIEW

**Comment by nilsga** [comment]
The tests fails locally without any modifications to master, so I can't say wether this fix introduces new test errors or not.

**Comment by dpsoft** [comment]
@nilsga  thanks for this PR! Just need to ask you please squash your commits and amend the message to something like `"! core: cleanup entity on removal"` and will merge right away, just to match our commit message conventions and please sign our [CLA] and we are good to go!

[CLA]: https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform

**Comment by nilsga** [comment]
Will do. Note that this fix only fixes the leak within `removeEntity`. There might be other `remove*`methods that needs the same fix.

**Comment by ivantopo** [comment]
Thanks a lot @nilsga! We will carefully check for other places where we might need to cleanup as well, regards!

**Pull request merged**
