### PR TITLE
Add Apache HttpClient 4.x instrumentation

### PR DESCRIPTION
**Pull request by prajeenrg**
Contains instrumentation code compatible with Apache HttpClient 4.0 onwards.
All the tests written to confirm the tracing are passing.

### CODE REVIEW

**Comment by prajeenrg** [comment]
@hughsimpson could you please review this if possible?

**Comment by hughsimpson** [comment]
Look at me getting pings to review like a proper OSS maintainer 😂 tell you what @prajeenrg I'll check this out tomorrow if you do me a solid and give a once-over on the lib bumps I've proposed [here](https://github.com/kamon-io/Kamon/pull/1329)

**Comment by prajeenrg** [comment]
Looks like a proper OSS maintainer to me at least 😁🤦‍♂️. Your changes for version bumps looks good to me, doesn't seem like it will cause some havoc here.

**Comment by prajeenrg** [comment]
@hughsimpson are you good with the changes?

**Review by hughsimpson — APPROVED** [review]

**Comment by hughsimpson** [comment]
@prajeenrg LGTM! Sorry about the slight delay there

**Pull request merged**
