### PR TITLE
+ khronus: introduce system metrics and segments

### PR DESCRIPTION
**Pull request by dpsoft**

### CODE REVIEW

**Comment by dpsoft** [comment]
@crypticmind @cristianspinetta please review!!!!!!

**Comment by crypticmind** [comment]
👍  Looks good to me!

**Comment by dpsoft** [comment]
@crypticmind @cristianspinetta guys, please review!!!!

**Comment by crypticmind** [comment]
image

**Comment by cristianspinetta** [comment]
@dpsoft LGTM! I want to see this in action!!

**Comment by dpsoft** [comment]
@crypticmind @cristianspinetta I just published a snapshot version `0.6.4-d19ca19231f95a89d67c9241310028cb3973c298`

**Pull request merged**
