### PR TITLE
= Generic mem metrics

### PR DESCRIPTION
**Pull request by tferi**
Hey guys,

This is based on the pending PR https://github.com/kamon-io/Kamon/pull/244 so you need to see https://github.com/tferi/Kamon/compare/mempool-metrics...tferi:generic-mem-metrics for the relative changeset.

As the Memory metrics work the same way, I took the liberty to merge them into one class + companion object. I'll squash the changes if you approve this.

I'm late to the party so I'm missing a lot of context here, and something occurred to me. I noticed that most (all?) metrics are collected as side effects in class constructors while they could be done in regular functions. I'm curious why the design took this direction - doesn't this approach generate more workload for the GC?

### CODE REVIEW

**Comment by ivantopo** [comment]
Hello @tferi! I like the approach, it simplifies things here so go ahead and polish it so we can merge it :). 

Also, I don't get exactly what you mean by "I noticed that most (all?) metrics are collected as side effects in class constructors while they could be done in regular functions.", in all the entity recorders' constructors we are not actually recording anything, but rather creating a little function that is later called periodically to get the metric values and record them in their proper instruments. It seemed to be the easiest and shorter way to define those entity recorders but if you see something better please let us know! We are always open to improvements :D

**Comment by dpsoft** [comment]
@tferi  thanks for this PR! Just need to ask you please squash your commits and amend the message to something like `"= system-metrics: Generic mem metrics "` and will merge right away  and we are good to go!

**Comment by tferi** [comment]
@ivantopo I guess I misunderstood the code then, sorry about that! I've squashed those commits, is the PR okay now?

**Comment by ivantopo** [comment]
Thanks for this contribution :), hope to see more coming!

**Pull request merged**
