### PR TITLE
Clean up attachment provider paths so that to process works for jre n…

### PR DESCRIPTION
**Pull request by zettelmj**
…ot just jdk

### CODE REVIEW

**Comment by zettelmj** [comment]
Fixes #440. Run it locally on linux with openjdk jre and jdk installations, an oracle jdk installation and on a mac.

**Comment by dpsoft** [comment]
@zettelmj   thanks for proposing this PR, please sign our [CLA](https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform) and  we are good to go!

**Comment by zettelmj** [comment]
Done

**Comment by dpsoft** [comment]
@zettelmj thanks for proposing this PR!

**Pull request merged**
