### PR TITLE
system-metrics: fix #148, file descriptor leak in context switches

### LINKED ISSUE #148: kamon-system-metrics: context switches metric causes file descriptor leak
In SystemMetricsCollector.scala we have the following loop
```
val filename = s"/proc/$pid/status"
...
for (line ← Source.fromFile(filename).getLines()) {
```
Source is an infamous scala.io.Source which is known for not closing files after they are used. Running application with context switches metric enabled and using "lsof -p PID" clearly shows growing number of open "/proc/PID/status" files. Eventually this leads to "too many open files" errors.

### PR DESCRIPTION
**Pull request by pikazlou**
Fix for #148

### CODE REVIEW

**Comment by ivantopo** [comment]
Hello @pikazlou, thanks a lot for fixing this issue! I need to ask you to please sign our CLA and wait a bit to merge this, I made a big mistake on merging a experimental branch on master and everything is a mess there now :(, I guess in a couple of days everything will be in place and ready to merge this :) thanks!

**Comment by pikazlou** [comment]
Which way can I sign? Should I print PDF, sign and scan?

**Comment by ivantopo** [comment]
No need to print and scan, just sign it electronically: https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform

**Comment by pikazlou** [comment]
signed

**Comment by dpsoft** [comment]
@pikazlou thanks for this PR!!

**Pull request merged**
