### PR TITLE
Allow accessing tags on Span.Local

### PR DESCRIPTION
**Pull request by nadavwr**
Used to be possible in 0.6.x (see #386)

### CODE REVIEW

**Comment by nadavwr** [comment]
Locally, `+test` seems to pass just fine. What could be failing the build?

**Comment by nadavwr** [comment]
Sporadic test failures occur also with vanilla 1.0 for the same tests

**Comment by ivantopo** [comment]
Hello Nadav!

There are big differences between the old TraceContext/Segments and the new Context/Span infrastructure. Before users would add information to the TraceContext and then be able to retrieve it at any point where the same TraceContext was available because there was always the very same TraceContext instance available for a single request. Now that we have Spans instead, a single request might be generating several Spans and putting data in one Span doesn't mean that you can retrieve it down the road because there might be a different current span down there.

We introduced the `Context` abstraction for these specific cases and all our instrumentation is passing the Context all over the place, regardless of tracing being available or not. The migration path that see from here is to move user data from the old TraceContext/Segment to the new Context.

Could you please share a bit more of what motivated this PR and whether the explanation above covers the use case?

**Comment by ivantopo** [comment]
Hey @nadavwr, looking forward to your comments!

**Comment by nadavwr** [comment]
Hi Ivan,
Our original intent had been to reflect span tags in MDC. Being able to peek into span context seemed like an absent feature.
We have since abandoned our initial focus on using span—`TraceContext` is adequate for our needs. This still seems "nice to have" though :)

**Comment by ivantopo** [comment]
@nadavwr did you mean `Context` instead? the `TraceContext` is from 0.6! 

I'm going to close this PR then, but there is something I would like to understand: Do you actually need certain things to be on the MDC or you just need them to be logged? Also, there is a conversation [on the kamon-logback module](https://github.com/kamon-io/kamon-logback/pull/4) that might be interesting to you if on the need to put stuff on the MDC.

**Comment by nadavwr** [comment]
We skip the MDC and have them logged from context

**Comment by ivantopo** [comment]
thanks for the feedback :)

**Pull request closed without merging**
