### PR TITLE
[issue 443] actor system terminate

### PR DESCRIPTION
**Pull request by pjfanning**
https://github.com/kamon-io/Kamon/issues/443

### CODE REVIEW

**Comment by dpsoft** [comment]
@pjfanning looks good to me! @ivantopo WDYT?

**Comment by pjfanning** [comment]
https://github.com/akka/akka/blob/release-2.4/akka-actor/src/main/scala/akka/actor/ActorSystem.scala indicates that akka 2.4 still has the shutdown method but akka 2.5 removes it so it might still be useful to proceed. Another way to approach this would be to use reflection. If the build was done with akka 2.4 or 2.5 then the catch block could use reflection to call the shutdown method.

**Comment by ivantopo** [comment]
we will soon be removing Akka from kamon-core (or at least, we want to)... so this won't be a long term problem. I'm fine with getting the proposed fix by @pjfanning, but there wont be need to get into reflection in the future!

**Comment by ivantopo** [comment]
hey @pjfanning, thanks a lot for everything! I see you helping with PRs, answering questions to other people, thanks a lot for all your efforts! :smile:

**Comment by pjfanning** [comment]
Thanks @ivantopo, @dpsoft for all the hard work you've put in to making Kamon such a valuable monitoring tool.

**Pull request merged**
