### PR TITLE
update kamon-play-example to latest version

### PR DESCRIPTION
**Pull request by jtjeferreira**

### CODE REVIEW

**Comment by dpsoft** [comment]
@jtjeferreira thanks for this PR! I just need to ask you to change the commit message to something like `= play-example: update to latest version`, just to match our commit message conventions.

**Comment by jtjeferreira** [comment]
updated the commit message

**Comment by dpsoft** [comment]
@jtjeferreira I just need to ask you to sign our [CLA] and we are good to go!

[CLA]: https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform

**Comment by jtjeferreira** [comment]
@dpsoft signed it

**Comment by dpsoft** [comment]
@jtjeferreira merged!!!

**Pull request merged**
