### PR TITLE
Run tests on PR 

### PR DESCRIPTION
**Pull request by SimunKaracic**
Perhaps it would be useful to run tests on pull-request, not only on direct push. 

WDYT?

### CODE REVIEW

**Comment by ivantopo** [comment]
Good, we needed this!

**Comment by ivantopo** [comment]
image

hey @SimunKaracic, can you please check the error above? I actually thought the name was right :confused:

**Comment by SimunKaracic** [comment]
I tested it out on my fork and it worked :/ 
checking it out now :+1:

**Comment by ivantopo** [comment]
I think it should have been `pull_request` instead.

**Comment by SimunKaracic** [comment]
Yeah I messed up when cleaning up after testing. Pushing fix

**Pull request merged**
