### PR TITLE
+ statsd: scale statsd time and memory values to values from config

### PR DESCRIPTION
**Pull request by jozic**
this is an attempt to fix part of #111 

@ivantopo @dpsoft please review
please note changes to Memory UnitOfMeasurement

if this looks okay, i can send another PR for datadog module

### CODE REVIEW

**Comment by dpsoft** [comment]
@jozic LGTM. @ivantopo WDYT?

**Comment by ivantopo** [comment]
hey @jozic, this looks good to me! The only thing that I kind of not like is the name of the settings and feature.. the word "rescale" sounds like if things were already scaled and need to be scaled again. I would go for a simpler config name like "memory-units" and "time-units" that default to Nanoseconds and Bytes, respectively. WDYT?

Other than that, I'm happy with the approach, thanks! :D

**Comment by jozic** [comment]
sure, no problem, will rename things

**Comment by jozic** [comment]
hey @dpsoft @ivantopo 
i did renaming according to your suggestion...

But i also tried another approach in a separate branch. 
The idea is to have an intermediate actor which scales TickMetricSnapshot (via InstrumentationSnapshots) before forwarding to a sender.
It adds one more actor in chain, but decouples scaling from any sender, and can be easily used for any backend. Please take a look here https://github.com/jozic/Kamon/commit/761ae0e7db07244ddade3402bcf8e0dbc85a8d37 and let me know what you think. i will add more tests and docs if you think we should move this way

**Comment by jozic** [comment]
@ivantopo @dpsoft ping, 
i know you guys are busy, but would like to finish this before next release

**Comment by jozic** [comment]
closed in favor of #294

**Pull request closed without merging**
