### PR TITLE
Corrects key name error in JMX reference configuration

### PR DESCRIPTION
**Pull request by maesenka**

### CODE REVIEW

**Comment by dpsoft** [comment]
@maesenka  thanks for proposing this fix.!! please sign our [CLA] and we are good to go.



[CLA]:https://docs.google.com/forms/d/1G_IDrBTFzOMwHvhxfKRBwNtpRelSa_MZ6jecH8lpTlc/viewform

**Comment by maesenka** [comment]
Signed it

**Comment by maesenka** [comment]
Btw, also the Fluentd module has the same problem.

**Comment by dpsoft** [comment]
@maesenka thanks!!!

**Pull request merged**
