### PR TITLE
+ add spm metric backend

### PR DESCRIPTION
**Pull request by whiter4bbit**
Added backend for sending Kamon Akka metrics to SPM (http://sematext.com/spm/index.html).

### CODE REVIEW

**Comment by ivantopo** [comment]
hey @whiter4bbit, thanks for proposing this! The PR looks fine, I did a quick review and everything seems to be in place. The fact that we have very little documentation regarding creating new modules and still you got everything in place at first try is a very nice touch, kudos!

There is only one thing that I would like to talk about before merging: support. We do not use Sematext at the moment and we have no prior experience with the tool, but in theory if we publish `kamon-spm` as an official Kamon module we should be able to provide some basic support for it, at least on the Kamon side.. do you have availability to give a hand to Kamon users when they try to use this module?

**Comment by whiter4bbit** [comment]
@ivantopo, thanks. Yes, sure we can provide support here is our support email - spm-support@sematext.com. Also we have Olark chat embedded in all our pages, so we can help users with Kamon+spm integration. Btw, there is one more PR pending - https://github.com/sematext/kamon.io/commit/37b0618c6aa69615b487d6ae9b25b614d677d213 with documentation page.

**Comment by dpsoft** [comment]
@whiter4bbit done. BTW: what is the posibility that kamon logo appears in your site in integrations? ;), and also we waiting for documentation PR.

**Comment by otisg** [comment]
@dpsort - logo at http://sematext.com/spm and on http://sematext.com/spm/integrations/ - we'll be adding it next week!

**Comment by dpsoft** [comment]
@otisg great!!!!!.

**Comment by otisg** [comment]
@dpsoft there it is, Kamon logo: http://sematext.com/spm/integrations/ .  Thanks for the speedy merge!
Any idea when 0.5.0 will be out?  Asking because I think we need to wait with SPM+Kamon+Akka announcement until Kamon 0.5.0 with the SPM backend is released.

**Comment by dpsoft** [comment]
@otisg awesome!!!. but the logo is a little weird but doesn't matter, if you have time you can take this [logo].
In relation a the Release we hope to do this weekend. But the release version is 0.4.1. ;) @ivantopo WDYT.

[logo]:https://www.typesafe.com/partners/technology-partners

**Pull request merged**
