### PR TITLE
Added trace-errors, http, trace-segments and custom metrics support for SPM

### PR DESCRIPTION
**Pull request by qkoshelev**

### CODE REVIEW

**Comment by otisg** [comment]
Checks passed, no conflicts... any chance this could be merged @dpsoft ?

**Comment by dpsoft** [comment]
@otisg yes, I will review this tonight.

**Comment by dpsoft** [comment]
@qkoshelev @otisg done!!!

**Comment by dpsoft** [comment]
@otisg @qkoshelev  we just published the Kamon [0.6.3] version with this PR. Thanks and sorry for the late response!!

[0.6.3]:http://search.maven.org/#artifactdetails%7Cio.kamon%7Ckamon-core_2.11%7C0.6.3%7C

**Pull request merged**
