### PR TITLE
+kafka: permit specifying custom propagation implementation

### PR DESCRIPTION
**Pull request by hughsimpson**

### CODE REVIEW

**Comment by yarosman** [comment]
relates to

**Comment by hughsimpson** [comment]
@yarosman I think b3 should be pretty similar to the custom implementation I made for the test -- if you're up for implementing it, I'll happily accept a pr to my branch (although I don't need it myself)

**Comment by yarosman** [comment]
@ivantopo What do you think about merging it ?

**Comment by hughsimpson** [comment]
Think Ivan's a bit busy with other stuff at the moment so might take a while to get to this - I've been overriding the class locally in the meantime

**Comment by hughsimpson** [comment]
@yarosman released as 2.6.4, lemme know how it goes

**Comment by yarosman** [comment]
> @yarosman released as 2.6.4, lemme know how it goes

I hope I will try to integrate it on next week ))

**Pull request merged**
